---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
# This is the setup chunk
#  Here you can set global options for the entire document

library(knitr) # I recommend doing this here
library(tidyverse)
library(sf)
library(leaflet)
library(ggplot2)
library(tigris)
library(arcgislayers)
library(tidycensus)

options(tigris_use_cache = TRUE)

# Although you can call functions from a library using the following notation
#  without loading the entire library.
knitr::opts_chunk$set(echo = TRUE, 
                      tidy = TRUE,
                      tidy.opts = list(width.cutoff = 60),
                      comment = NA, # Required
                      fig.path = "./figures/",  # Store all figures here in relative path (make the folder first)
                      fig.align = "center",
                      fig.width = 7,
                      fig.height = 7,
                      message = FALSE, # Turn off load messages
                      warning = FALSE # Turn off warnings
                      )

```

```{r}
# stores tiger shapefile for VA in 2025
va_counties <- counties(state = "51", year = 2025)
# loops and collects bodies of water for every county
va_water_list <- purrr::map(va_counties$COUNTYFP, ~ {area_water(state = "51", county = .x, year = 2025)})
# binds everything together and changes coordinate system
va_water <- dplyr::bind_rows(va_water_list) %>% st_transform(crs = 4326)

# getting electric grid shapefile from arcgis **(last updated 2023)
url <- "https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Electric_Power_Transmission_Lines/FeatureServer/0"
layer <- arc_open(url)
elecGridData <- arc_select(layer)

# takes elecGridData layer, changes coordinate system, sets boundary to reduce processing time
va_lines <- elecGridData %>% st_transform(crs = 4326) %>% st_filter(st_as_sfc(st_bbox(va_water)))
```

```{r}
# reads data center dataset and sets lat and long columns to sf object and correct coordinate system
data_centers <- read.csv("data/clean01_datacenter.csv") %>% st_as_sf(coords = c("longitude", "latitude"), crs = 4326)
```

```{r}
# reads in large land parcel shapefile 
land <- st_read("data/final_shapes/final_shapes.shp")
```


```{r}
# exploratory leaflet map with electric grid and bodies of water

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron, group = "Base Map") %>%
  
  # bodies of water
  addPolygons(data = va_water, color = "blue", weight = 1, fillOpacity = 0.6, group = "Area Water") %>%
              
  # electric lines
  addPolylines(data = va_lines, color = "red", weight = 2, opacity = 0.8, group = "Transmission Lines") %>%
  
  # data centers (top layer), zIndexOffset in options is set to a high value to have this layer appear above the other layers
  addCircleMarkers(data = data_centers, color = "black", weight = 1, radius = 3, fillOpacity = 1, options = markerOptions(zIndexOffset = 10), group = "Data Centers") %>%
  
  # large land parcels 
  addPolygons(data = land, color = "forestgreen", weight = 1, fillOpacity = 1, group = "Large Land Parcels") %>%

  # layer controls
  addLayersControl(overlayGroups = c("Area Water", "Transmission Lines", "Data Centers", "Large Land Parcels"), options = layersControlOptions(collapsed = FALSE))

```

